apiVersion: v1
kind: Service
metadata:
  name: < service_name >
  labels:
    < label_name >: < label_value >
spec:
  ports:
    - protocol: TCP
      port: < cluster_ip_port >
      targetPort: < target_port >
  selector:
    < target_pod_label_name >: < target_pod_label_value >

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: < statefulset_name >
spec:
  selector:
    matchLabels:
      < label_name >: < label_value > # has to match .spec.template.metadata.labels
  serviceName: < service_name > # required
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        < label_name >: < label_value> # has to match .spec.selector.matchLabels
    spec:
      # terminationGracePeriodSeconds: 10
      containers:
      - name: < container_name >
        image: < pod_image >
        volumeMounts:
        - name: < claim_name >
          mountPath: < path_to_mount_on_container
  volumeClaimTemplates:
  - metadata:
      name: < claim_name >
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi