apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: < persistent_volume_claim_name >
  namespace: < namespace_name >
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi